name: Auto Merge PRs

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get modified files
        run: |
          MODIFIED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "$MODIFIED_FILES" > modified_files.txt

      - name: Check and merge
        run: |
          if [[ $(cat modified_files.txt) == "ejercicio.cs" ]]; then
            echo "Only ejercicio.cs modified. Merging PR."
            gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch
          else
            echo "Other files modified. Skipping merge."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}